 # Makefile for Cracking the Coding interview questions 

all: ds sh

ds: testing.c linkedlist.c
	gcc -g -Wall -o ds testing.c linkedlist.c

#sh: sh_kyle.c linkedlist.c
#gcc -g -Wall -o sh sh_kyle.c linkedlist.c


