 # Makefile for Cracking the Coding interview questions 

all: ksh

#ds: testing.c linkedlist.c
#	gcc -g -Wall -o ds testing.c linkedlist.c

ksh: ksh.c linkedlist.c ksh_split_line.c 
	gcc -g -Wall -o ksh ksh.c ksh_split_line.c 



