 # Makefile for Cracking the Coding interview questions 

all: sh

#ds: testing.c linkedlist.c
#	gcc -g -Wall -o ds testing.c linkedlist.c

sh: sh_kyle.c linkedlist.c stringtolist.c usrfunc.c
	gcc -g -Wall -o ks sh_kyle.c linkedlist.c stringtolist.c usrfunc.c



